[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nathan-python-courses"
version = "2023.12.30"

dependencies = [
  "pytest",
  "coverage",
  "pytest-cov"
]

requires-python = ">= 3.9"

[tool.pytest]
testpaths = ["sncb/tests/"]